[Job]
docker_command="/app/script.sh {task_input} {job_id}"
job_id_prefix="my_exp_12_"
task_interval="0"

[Pool]
autoscale="False"
container_image_name="cfaprdbatchcr.azurecr.io/cfa-metaflow:latest"
dedicated_nodes="5"
input_mount="input-test"
low_priority_nodes="0"
max_autoscale_nodes="5"
output_mount="output-test"
parallel_pool_limit="1"
pool_name_prefix="my_exp_12_"
task_slots_per_node="1"
vm_size="STANDARD_D4d_V5"
