[Authentication]
subscription_id="REPLACE_WITH_AZURE_SUBSCRIPTION_ID"
resource_group="REPLACE_WITH_AZURE_RESOURCE_GROUP"
user_assigned_identity="REPLACE_WITH_USER_ASSIGNED_ID"
tenant_id="REPLACE_WITH_TENANT_ID"
batch_application_id="REPLACE_WITH_BATCH_APP_ID"
batch_object_id="REPLACE_WITH_BATCH_OBJECT_ID"
sp_application_id="REPLACE_WITH_SERVICE_PRINCIPAL_APP_ID"
vault_url="REPLACE_WITH_AZURE_VAULT_URL"
vault_sp_secret_id="REPLACE_WITH_SECRET_ID"
subnet_id="REPLACE_WITH_AZURE_SUBNET_ID"

[Batch]
batch_account_name="REPLACE_WITH_BATCH_ACCOUNT"
batch_service_url="REPLACE_WITH_BATCH_SERVICE_URL"
job_id="my_states_job_id_3"
parallel_pool_limit="4"
pool_name="REPLACE_WITH_POOL_NAME"
pool_name_prefix="REPLACE_WITH_POOL_NAME_PREFIX"
pool_vm_size="STANDARD_A2_V2"
task_interval="10"
scaling_mode="fixed"

[Container]
container_registry_url="URL_FOR_CONTAINER_REGISTRY"
container_registry_server="CONTAINER_REGISTRY_SERVER"
container_registry_username="USER_NAME_FOR_CONTAINER_REGISTRY"
container_registry_password="PASSWORD_FOR_CONTAINER_REGISTRY"
container_image_name="CONTAINER_IMAGE_NAME"

[Storage]
storage_account_name="AZURE_BLOB_STORAGE_ACCOUNT"
storage_account_url="AZURE_BLOB_STORAGE_URL"